# Generated by Django 4.2.4 on 2025-10-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImage', models.ImageField(blank=True, null=True, upload_to='../../DumpFiles')),
                ('userAnswer', models.CharField(max_length=30)),
            ],
        ),
    ]
